apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: egress-internal
spec:
  protocol: IPv4
  cidrBlock: 172.20.10.0/24
  gateway: 172.20.10.1
  excludeIps:
    - 172.20.10.1
  natOutgoing: false
  private: false
  provider: ovn-internal.default.ovn
  vpc: ovn-cluster
