---
apiVersion: v1
kind: Secret
metadata:
  name: test-b1-cloudinit
  namespace: tenant-b
  labels:
    harvesterhci.io/cloud-init-template: harvester
type: secret
stringData:
  userdata: |
    #cloud-config
    users:
      - default
      - name: opensuse
        groups: wheel
        lock_passwd: false
        passwd: $y$j9T$2QWCRp2ljG.y0d3Kp/eLm/$4g/WcpvcgZSQO4MALxSgvLwujMt7GFV.ITlBEpydAbB
        sudo: "ALL=(ALL) NOPASSWD:ALL"
        shell: /bin/bash
        ssh_authorized_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAqqOTnQH64QLG3W7Zz93lNfYHUfO5JJtM724URLkjZm coulof@suse
    ssh_pwauth: true
    package_update: true
    packages:
      - qemu-guest-agent
      - curl
      - traceroute
    runcmd:
      - [systemctl, enable, --now, qemu-guest-agent.service]
  networkdata: ""
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test-b1
  namespace: tenant-b
  labels:
    harvesterhci.io/creator: harvester
    harvesterhci.io/os: linux
  annotations:
    harvesterhci.io/vmRunStrategy: RerunOnFailure
    harvesterhci.io/volumeClaimTemplates: >-
      [{"metadata":{"name":"test-b1-disk-0","annotations":{"harvesterhci.io/imageId":"default/opensuse-leap-15-6"}},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"10Gi"}},"volumeMode":"Block","storageClassName":"longhorn-opensuse-leap-15-6"}}]
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      labels:
        harvesterhci.io/vmName: test-b1
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: disk-0
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - name: overlay
              model: virtio
              bridge: {}
        machine:
          type: q35
        memory:
          guest: 1Gi
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 125m
            memory: 512Mi
      networks:
        - name: overlay
          multus:
            networkName: tenant-b/egress-internal
      terminationGracePeriodSeconds: 120
      volumes:
        - name: disk-0
          persistentVolumeClaim:
            claimName: test-b1-disk-0
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: test-b1-cloudinit
