apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: egress-external-a
spec:
  protocol: IPv4
  cidrBlock: 192.168.31.0/24
  gateway: 192.168.31.1
  provider: egress-ext.tenant-a.ovn
  vlan: vlan0-ext
  vpc: ovn-cluster
  natOutgoing: false
  excludeIps:
    - 192.168.31.1..192.168.31.100
    - 192.168.31.111..192.168.31.254
